<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;ArduinoController;ScalemonViewer</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.Authentication.Basic" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.8" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.8" />
    <PackageReference Include="Radzen.Blazor" Version="7.4.1" />
    <PackageReference Include="Serilog" Version="4.3.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.2" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scalemon.ApiService\Scalemon.ApiService.csproj" />
    <ProjectReference Include="..\Scalemon.Common\Scalemon.Common.csproj" />
    <ProjectReference Include="..\Scalemon.DataAccess\Scalemon.SqlDataAccess.csproj" />
    <ProjectReference Include="..\Scalemon.FSM\Scalemon.FSM.csproj" />
    <ProjectReference Include="..\Scalemon.SerialLink\Scalemon.SerialLink.csproj" />
    <ProjectReference Include="..\Scalemon.SignalBus\Scalemon.SignalBus.csproj" />
    <ProjectReference Include="..\Scalemon.WebApp\Scalemon.WebApp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
